#!/usr/bin/env python3
"""Render every brand asset from the geometry and palette defined here.

    python3 tool/gen_brand_assets.py

The mark is two polygons on a 64x64 grid, cropped to the art box 9,5 46x51.
Nothing else in the repo carries that geometry, so this file is the source of
truth: change a coordinate here and re-run, never touch the generated PNGs.

Rasterising goes through headless Chrome because it is the only SVG renderer
this project can assume on macOS. Every size is rendered from the vector rather
than downscaled from one master, so the diagonals stay crisp at 16 px.
"""

from __future__ import annotations

import shutil
import struct
import subprocess
import sys
import tempfile
from base64 import b64encode
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "brand"
ICONS = OUT / "appicons"

CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

# ---- geometry ----------------------------------------------------------------
# Two planes cut by one diagonal, both remates falling on a single line.
BACK = "9,17 33,10.7 25,56 9,56"
FRONT = "40,8.9 55,5 55,56 32,56"
ART = (9, 5, 46, 51)  # x, y, w, h — the tight box around both polygons

# ---- palette -----------------------------------------------------------------
ON_LIGHT = ("#14208f", "#4aa8ee")   # deep blue behind, sky in front
ON_DARK = ("#3350e0", "#4aa8ee")    # deep blue drowns on dark grounds, so it lifts
ICON_GROUND = "#14208f"
ON_ICON = ("#4aa8ee", "#eaf4ff")

WORDMARK_INK = {"light": "#14208f", "dark": "#eceff2"}


README = """# Brand assets

GENERATED by `tool/gen_brand_assets.py`. Do not edit anything in this folder:
change the geometry or the palette in that script and re-run it, or the mark
starts drifting between platforms. Re-running deletes and rewrites the folder.

    python3 tool/gen_brand_assets.py

## The mark

Two planes cut by one diagonal, both top edges falling on a single line. The
separation is air, not colour, so the mark needs no outline version — the
one-ink file is the same drawing.

| role        | on light  | on dark   | on the icon ground |
| ----------- | --------- | --------- | ------------------ |
| back plane  | `#14208f` | `#3350e0` | `#4aa8ee`          |
| front plane | `#4aa8ee` | `#4aa8ee` | `#eaf4ff`          |
| icon ground | —         | —         | `#14208f`          |

The deep blue drowns below `#1a1f26`, which is why the dark variant lifts the
back plane to `#3350e0` instead of recolouring both.

## Using it in the app

`agora-mark.png` ships at 1x with `2.0x/` and `3.0x/` beside it, so Flutter
resolves the density on its own. List the files one by one in `pubspec.yaml` —
never the folder, or the whole of `appicons/` ends up inside the bundle:

    assets:
      - assets/brand/agora-mark.png
      - assets/brand/agora-mark-dark.png

`agora-mark-mono.svg` paints with `currentColor`, for anywhere the mark has to
inherit the surrounding ink.

## Lockup

The wordmark is Manrope ExtraBold, which the app already bundles, so build the
lockup live instead of shipping the PNG wherever you can. For a mark of height
H: gap `0.30 H`, font size `0.63 H`, letter-spacing `-0.035em`, ink `#14208f`
on light and `#eceff2` on dark. The PNGs exist for README files, stores and
anything outside the app.

## App icons

Every file under `appicons/` is already named the way its platform expects, so
installing them is a copy. All six platforms are wired up; this is what to
re-run after changing the geometry:

    cp -R assets/brand/appicons/ios/.     ios/Runner/Assets.xcassets/AppIcon.appiconset/
    cp -R assets/brand/appicons/macos/.   macos/Runner/Assets.xcassets/AppIcon.appiconset/
    cp    assets/brand/appicons/web/Icon-*.png    web/icons/
    cp    assets/brand/appicons/web/favicon.png   web/favicon.png
    cp -R assets/brand/appicons/android/. android/app/src/main/res/
    cp    assets/brand/appicons/windows/app_icon.ico  windows/runner/resources/

The web icons go into `web/icons/`, not next to `index.html`: that is where
`web/manifest.json` and the `apple-touch-icon` link point, and `favicon.png` is
the one file that sits at the root. `tool/build_site.py` copies both out of
`web/` into the landing build, so the site and the app shell can never show
different icons.

iOS icons are opaque and full bleed because iOS applies its own mask. macOS
draws the file as it is, so those carry their own rounded rect and margin. The
maskable web icons keep the mark inside the safe circle.

Android composes its own launcher icon from the two layers in
`mipmap-anydpi-v26/ic_launcher.xml`, with the ground declared as a colour in
`values/colors.xml` — both already in the repo. The flat `ic_launcher.png`
files beside them are the fallback for anything older than API 26.
"""


def mark_svg(colors: tuple[str, str], width: float, height: float) -> str:
    x, y, w, h = ART
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{x} {y} {w} {h}" '
        f'width="{width:g}" height="{height:g}">'
        f'<polygon points="{BACK}" fill="{colors[0]}"/>'
        f'<polygon points="{FRONT}" fill="{colors[1]}"/>'
        f"</svg>"
    )


def icon_svg(px: int, *, frac: float, radius: float, inset: float = 0.0) -> str:
    """A square app icon: the mark centred on the brand ground.

    frac   height of the mark as a share of the canvas
    radius corner radius as a share of the canvas (0 = square, OS masks it)
    inset  transparent margin as a share of the canvas (macOS wants one)
    """
    side = 64 * (1 - 2 * inset)
    off = 64 * inset
    scale = 64 * frac / ART[3]
    w = ART[2] * scale
    x = (64 - w) / 2 - ART[0] * scale
    y = (64 - 64 * frac) / 2 - ART[1] * scale
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" '
        f'width="{px}" height="{px}">'
        f'<rect x="{off:g}" y="{off:g}" width="{side:g}" height="{side:g}" '
        f'rx="{side * radius:g}" fill="{ICON_GROUND}"/>'
        f'<g transform="translate({x:.4f} {y:.4f}) scale({scale:.6f})">'
        f'<polygon points="{BACK}" fill="{ON_ICON[0]}"/>'
        f'<polygon points="{FRONT}" fill="{ON_ICON[1]}"/>'
        f"</g></svg>"
    )


def foreground_svg(px: int) -> str:
    """Android adaptive foreground: the mark alone, the ground set in XML."""
    scale = 64 * 0.38 / ART[3]
    w = ART[2] * scale
    x = (64 - w) / 2 - ART[0] * scale
    y = (64 - 64 * 0.38) / 2 - ART[1] * scale
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" '
        f'width="{px}" height="{px}">'
        f'<g transform="translate({x:.4f} {y:.4f}) scale({scale:.6f})">'
        f'<polygon points="{BACK}" fill="{ON_ICON[0]}"/>'
        f'<polygon points="{FRONT}" fill="{ON_ICON[1]}"/>'
        f"</g></svg>"
    )


def lockup_html(mode: str, mark_h: int) -> str:
    """Mark plus wordmark, laid out with the real Manrope so the PNG is exact."""
    ttf = (ROOT / "assets/fonts/Manrope-ExtraBold.ttf").read_bytes()
    data = "data:font/ttf;base64," + b64encode(ttf).decode()
    colors = ON_LIGHT if mode == "light" else ON_DARK
    w = ART[2] / ART[3] * mark_h
    return f"""<!doctype html><meta charset="utf-8"><style>
@font-face {{ font-family: Manrope; font-weight: 800; src: url({data}) format('truetype'); }}
html, body {{ margin: 0; height: 100%; background: transparent; }}
.lockup {{
  display: flex; align-items: center; justify-content: center; gap: {mark_h * 0.30:g}px;
  height: 100%; font-family: Manrope; font-weight: 800;
}}
.word {{ font-size: {mark_h * 0.63:g}px; letter-spacing: -0.035em; line-height: 1;
  color: {WORDMARK_INK[mode]}; }}
svg {{ display: block; }}
</style>
<div class="lockup">{mark_svg(colors, w, mark_h)}<span class="word">Agora</span></div>"""


def render(html: str, dest: Path, width: int, height: int) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        page = Path(tmp) / "page.html"
        page.write_text(html, encoding="utf-8")
        subprocess.run(
            [CHROME, "--headless", "--disable-gpu", "--hide-scrollbars",
             "--default-background-color=00000000",
             f"--window-size={width},{height}",
             f"--screenshot={dest}", str(page)],
            check=True, capture_output=True,
        )


def render_svg(svg: str, dest: Path, width: int, height: int) -> None:
    render(f'<!doctype html><meta charset="utf-8">'
           f"<style>html,body{{margin:0;background:transparent}}"
           f"svg{{display:block}}</style>{svg}", dest, width, height)


def write_ico(sizes: list[int], dest: Path) -> None:
    """Pack PNG-compressed entries, which Windows has accepted since Vista."""
    with tempfile.TemporaryDirectory() as tmp:
        blobs = []
        for px in sizes:
            frame = Path(tmp) / f"{px}.png"
            render_svg(icon_svg(px, frac=frac_for(px), radius=0.18), frame, px, px)
            blobs.append((px, frame.read_bytes()))
        offset = 6 + 16 * len(blobs)
        header = struct.pack("<HHH", 0, 1, len(blobs))
        entries, payload = b"", b""
        for px, blob in blobs:
            entries += struct.pack(
                "<BBBBHHII", px if px < 256 else 0, px if px < 256 else 0,
                0, 0, 1, 32, len(blob), offset)
            offset += len(blob)
            payload += blob
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(header + entries + payload)


def frac_for(px: int) -> float:
    """Small canvases give the diagonal cut fewer pixels, so the mark grows."""
    if px <= 32:
        return 0.68
    if px <= 64:
        return 0.62
    return 0.56


IOS = {
    "Icon-App-20x20@1x.png": 20, "Icon-App-20x20@2x.png": 40,
    "Icon-App-20x20@3x.png": 60, "Icon-App-29x29@1x.png": 29,
    "Icon-App-29x29@2x.png": 58, "Icon-App-29x29@3x.png": 87,
    "Icon-App-40x40@1x.png": 40, "Icon-App-40x40@2x.png": 80,
    "Icon-App-40x40@3x.png": 120, "Icon-App-60x60@2x.png": 120,
    "Icon-App-60x60@3x.png": 180, "Icon-App-76x76@1x.png": 76,
    "Icon-App-76x76@2x.png": 152, "Icon-App-83.5x83.5@2x.png": 167,
    "Icon-App-1024x1024@1x.png": 1024,
}
MACOS = [16, 32, 64, 128, 256, 512, 1024]
ANDROID = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
# Adaptive foregrounds are 108dp canvases whose centre 72dp is the only region
# guaranteed to survive the launcher's mask, so the mark stays well inside it.
ANDROID_ADAPTIVE = {"mdpi": 108, "hdpi": 162, "xhdpi": 216, "xxhdpi": 324,
                    "xxxhdpi": 432}
WINDOWS_ICO = [16, 24, 32, 48, 64, 128, 256]


def main() -> int:
    if not Path(CHROME).exists():
        print(f"Chrome not found at {CHROME}", file=sys.stderr)
        return 1
    if OUT.exists():
        shutil.rmtree(OUT)

    done = 0

    # --- vector, for anything that can take an SVG -----------------------------
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "agora-mark.svg").write_text(mark_svg(ON_LIGHT, *ART[2:]))
    (OUT / "agora-mark-dark.svg").write_text(mark_svg(ON_DARK, *ART[2:]))
    (OUT / "agora-mark-mono.svg").write_text(
        mark_svg(("currentColor", "currentColor"), *ART[2:]))

    # --- the mark as PNG, at Flutter's 1x/2x/3x --------------------------------
    for name, colors in (("agora-mark", ON_LIGHT), ("agora-mark-dark", ON_DARK)):
        for factor, folder in ((2, ""), (4, "2.0x"), (6, "3.0x")):
            w, h = ART[2] * factor, ART[3] * factor
            render_svg(mark_svg(colors, w, h), OUT / folder / f"{name}.png", w, h)
            done += 1
        w, h = ART[2] * 20, ART[3] * 20
        render_svg(mark_svg(colors, w, h), OUT / f"{name}-master.png", w, h)
        done += 1

    # --- lockups --------------------------------------------------------------
    for mode in ("light", "dark"):
        render(lockup_html(mode, 220), OUT / f"agora-lockup-{mode}.png", 880, 340)
        done += 1

    # --- app icons ------------------------------------------------------------
    ICONS.mkdir(parents=True, exist_ok=True)
    (ICONS / "agora-icon.svg").write_text(icon_svg(1024, frac=0.56, radius=0.0))
    render_svg(icon_svg(1024, frac=0.56, radius=0.0), ICONS / "master-1024.png", 1024, 1024)
    done += 1

    web = ICONS / "web"
    render_svg(icon_svg(32, frac=0.72, radius=0.0), web / "favicon.png", 32, 32)
    for px in (192, 512):
        render_svg(icon_svg(px, frac=0.56, radius=0.22), web / f"Icon-{px}.png", px, px)
        # Maskable art must survive a circular crop, so it sits inside the safe zone.
        render_svg(icon_svg(px, frac=0.44, radius=0.0),
                   web / f"Icon-maskable-{px}.png", px, px)
    done += 5

    for name, px in IOS.items():
        render_svg(icon_svg(px, frac=frac_for(px), radius=0.0), ICONS / "ios" / name, px, px)
        done += 1

    for px in MACOS:
        # macOS draws the icon as-is, so the rounded rect and its margin are ours.
        render_svg(icon_svg(px, frac=frac_for(px) * 0.8, radius=0.225, inset=0.098),
                   ICONS / "macos" / f"app_icon_{px}.png", px, px)
        done += 1

    for density, px in ANDROID.items():
        render_svg(icon_svg(px, frac=frac_for(px), radius=0.0),
                   ICONS / "android" / f"mipmap-{density}" / "ic_launcher.png", px, px)
        done += 1

    for density, px in ANDROID_ADAPTIVE.items():
        render_svg(foreground_svg(px), ICONS / "android" /
                   f"mipmap-{density}" / "ic_launcher_foreground.png", px, px)
        done += 1

    write_ico(WINDOWS_ICO, ICONS / "windows" / "app_icon.ico")
    done += 1

    (OUT / "README.md").write_text(README)
    print(f"{done} files written to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
