#!/usr/bin/env python3
"""Generates site/tokens.css from lib/ui/theme/tokens.dart.

The landing page is HTML and the app is Flutter, so the palette has to exist
twice. Generating one from the other is what keeps them the same colour: edit
tokens.dart, re-run this, and the marketing page follows the product instead of
drifting a shade away from it over a few releases.

Usage: python3 tool/gen_css_tokens.py
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "lib/ui/theme/tokens.dart"
OUT = ROOT / "site/tokens.css"

# `bg: Color(0xFFF8FAFD),` — the one shape every token in the file uses.
ENTRY = re.compile(r"(\w+):\s*Color\(0x([0-9A-Fa-f]{8})\)")


def scheme(body: str) -> dict[str, str]:
    out = {}
    for name, argb in ENTRY.findall(body):
        a, rgb = argb[:2], argb[2:]
        if a.upper() != "FF":
            sys.exit(f"{name} is not fully opaque (0x{argb}); teach this script alpha")
        out[name] = "#" + rgb.lower()
    return out


def kebab(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def block(colors: dict[str, str], indent: str) -> str:
    return "\n".join(f"{indent}--{kebab(k)}: {v};" for k, v in colors.items())


def main() -> None:
    text = SRC.read_text()
    # Slice the two AppTokens literals out of the `pizarra` palette rather than
    # scanning the whole file: the doc comments above it carry example colours.
    try:
        light_at = text.index("light: AppTokens(")
        dark_at = text.index("dark: AppTokens(")
    except ValueError:
        sys.exit("could not find the light/dark AppTokens literals in tokens.dart")

    light = scheme(text[light_at:dark_at])
    dark = scheme(text[dark_at:])

    if not light or set(light) != set(dark):
        sys.exit(f"light and dark do not carry the same tokens: {set(light) ^ set(dark)}")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(
        f"""/* GENERATED by tool/gen_css_tokens.py from lib/ui/theme/tokens.dart.
   Do not edit: change the Dart and re-run, or the page and the app it is
   selling stop being the same colour. */

:root {{
{block(light, "  ")}
  color-scheme: light dark;
}}

@media (prefers-color-scheme: dark) {{
  :root {{
{block(dark, "    ")}
  }}
}}
"""
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(light)} tokens x2)")


if __name__ == "__main__":
    main()
